model:
  base_learning_rate: 1.0e-4
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /mnt/g/checkpoints/v2-1_512-ema-pruned.ckpt
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False # we set this to false because this is an inference only config

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: False
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: /mnt/g/checkpoints/kl-f8.ckpt
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"
        pretrained: /mnt/g/checkpoints/clip/open_clip_pytorch_model.bin

condition_adaptor_config:
  mode: from_text
  cond_type: saliency
  image_dir: /path/to/image/dir
  cond_dir: /path/to/condition/dir
  text_dir: /path/to/synthetic/text
  val_image_dir: /path/to/val/image/dir
  val_cond_dir: /path/to/val/condition/dir
  val_text_dir: /path/to/val/synthetic/text
  val_diffusion_steps: [500, 1000]
  val_sample_freq: 100
  size: 64
  image_size: 512
  epochs: 100
  blocks: [[2, 4, 8], [2, 4, 8, 12]]
  downsample_factor: 8
  in_channels: 7040
  out_channels: 4
  time_channels: 256
  learning_rate: 0.0001