model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    ckpt_path: SD_CELEB_CHECKPOINT_PATH
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    concat_mode: false
    monitor: val/loss
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: SD_VQVAE_CHECKPOINT_PATH
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

condition_aligner_config:
  mode: unconditional
  cond_type: edge
  image_dir: CELEB_IMAGE_FILELIST_PATH
  cond_dir: CELEB_CONDITION_PATH
  text_dir: # Unused
  val_diffusion_steps: [500, 1000]
  val_sample_freq: 100
  size: 64
  image_size: 256
  epochs: 100
  blocks: [[2, 4, 8], [2, 4, 8, 12]]
  downsample_factor: 8
  in_channels: 4480
  out_channels: 3
  time_channels: 256
  learning_rate: 0.0001
